from ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get upgrade -y && apt-get -y install python3 python3-pip
RUN pip3 install msgpack
ENV PYTHONPATH "${PYTHONPATH}:/root/fluentbit-server-py"
WORKDIR /root
# COPY tests/ /root/tests
# COPY fluentbit_server/ /root/fluentbit_server

